[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "resume_analyzer"
version = "0.1.0"
description = "AI-powered resume analysis tool"
requires-python = ">=3.8"